export type SpoylzType = "Advanced" | "Simple" | "Normal";
export type SpoylzManagementStatus = "Active" | "Disabled";

export interface SpoylzManagementItem {
  id: string;
  title: string;
  thumbnailColor: string;
  lecturerName: string;
  category: string;
  department: string;
  amount: string;
  enrolledStudents: number;
  earnedByLecturer: string;
  earnedByInstitution: string;
  type: SpoylzType;
  dateCreated: string;
  courseCode: string;
  pricing: string;
  detailAmount: string;
  detailEarnedByLecturer: string;
  detailEarnedByInstitution: string;
  modules: number;
  lessons: number;
  status: SpoylzManagementStatus;
  description: string;
  whatTheyWillLearn: string[];
}

export const MOCK_SPOYLZ_MANAGEMENT: SpoylzManagementItem[] = [
  {
    id: "1",
    title: "Understanding Design Principles",
    thumbnailColor: "#F4C77B",
    lecturerName: "Tayo Adebanjo",
    category: "UI/UX Design",
    department: "Computer Science",
    amount: "₦20,000",
    enrolledStudents: 10,
    earnedByLecturer: "₦200,000",
    earnedByInstitution: "₦200,000",
    type: "Advanced",
    dateCreated: "12-02-2026",
    courseCode: "CHM 404",
    pricing: "Paid",
    detailAmount: "₦15,000",
    detailEarnedByLecturer: "₦200,000",
    detailEarnedByInstitution: "₦20,000",
    modules: 5,
    lessons: 10,
    status: "Active",
    description: "This course is for aspiring product designers",
    whatTheyWillLearn: ["Basics of design", "Principles of Design", "Basics of design"],
  },
  {
    id: "2",
    title: "Frontend Development",
    thumbnailColor: "#8FB7E8",
    lecturerName: "Ogunsola Omorinsola",
    category: "Frontend Development",
    department: "Computer Science",
    amount: "₦100,000",
    enrolledStudents: 50,
    earnedByLecturer: "₦500,000",
    earnedByInstitution: "₦500,000",
    type: "Simple",
    dateCreated: "12-02-2026",
    courseCode: "CSC 210",
    pricing: "Paid",
    detailAmount: "₦100,000",
    detailEarnedByLecturer: "₦500,000",
    detailEarnedByInstitution: "₦500,000",
    modules: 8,
    lessons: 24,
    status: "Active",
    description: "Learn to build modern, responsive web interfaces.",
    whatTheyWillLearn: ["HTML & CSS fundamentals", "JavaScript essentials", "Building responsive layouts"],
  },
  {
    id: "3",
    title: "CHM202- IUPAC Nomenclature",
    thumbnailColor: "#7DB7B0",
    lecturerName: "Albert Flores",
    category: "Medicine",
    department: "Computer Science",
    amount: "₦80,000",
    enrolledStudents: 20,
    earnedByLecturer: "₦1,600,000",
    earnedByInstitution: "₦1,600,000",
    type: "Simple",
    dateCreated: "12-02-2026",
    courseCode: "CHM 202",
    pricing: "Paid",
    detailAmount: "₦80,000",
    detailEarnedByLecturer: "₦1,600,000",
    detailEarnedByInstitution: "₦1,600,000",
    modules: 6,
    lessons: 18,
    status: "Active",
    description: "A deep dive into IUPAC naming conventions for organic compounds.",
    whatTheyWillLearn: ["Naming organic compounds", "Functional group priority", "Common exceptions"],
  },
  {
    id: "4",
    title: "Financial Literacy",
    thumbnailColor: "#E3A6A6",
    lecturerName: "Amarachi Eze",
    category: "Finance",
    department: "Computer Science",
    amount: "₦40,000",
    enrolledStudents: 90,
    earnedByLecturer: "₦850,000",
    earnedByInstitution: "₦850,000",
    type: "Normal",
    dateCreated: "12-02-2026",
    courseCode: "FIN 101",
    pricing: "Paid",
    detailAmount: "₦40,000",
    detailEarnedByLecturer: "₦850,000",
    detailEarnedByInstitution: "₦850,000",
    modules: 4,
    lessons: 12,
    status: "Active",
    description: "Practical money management for students.",
    whatTheyWillLearn: ["Budgeting basics", "Saving and investing", "Avoiding common debt traps"],
  },
  {
    id: "5",
    title: "BCH 404- Pharmacology",
    thumbnailColor: "#A6A6E3",
    lecturerName: "Yetunde Adeyemi",
    category: "Medicine",
    department: "Computer Science",
    amount: "₦30,000",
    enrolledStudents: 18,
    earnedByLecturer: "₦240,000",
    earnedByInstitution: "₦240,000",
    type: "Advanced",
    dateCreated: "12-02-2026",
    courseCode: "BCH 404",
    pricing: "Paid",
    detailAmount: "₦30,000",
    detailEarnedByLecturer: "₦240,000",
    detailEarnedByInstitution: "₦240,000",
    modules: 5,
    lessons: 15,
    status: "Active",
    description: "Core principles of drug action and pharmacokinetics.",
    whatTheyWillLearn: ["Drug absorption & metabolism", "Dose-response relationships", "Common drug interactions"],
  },
  {
    id: "6",
    title: "Entrepreneurship",
    thumbnailColor: "#F2C87A",
    lecturerName: "Chioma Davies",
    category: "Tech",
    department: "Computer Science",
    amount: "₦25,000",
    enrolledStudents: 100,
    earnedByLecturer: "₦1,500,000",
    earnedByInstitution: "₦1,500,000",
    type: "Simple",
    dateCreated: "12-02-2026",
    courseCode: "BUS 300",
    pricing: "Paid",
    detailAmount: "₦25,000",
    detailEarnedByLecturer: "₦1,500,000",
    detailEarnedByInstitution: "₦1,500,000",
    modules: 6,
    lessons: 20,
    status: "Active",
    description: "From idea to launch: building your first venture.",
    whatTheyWillLearn: ["Validating a business idea", "Building a lean business plan", "Pitching to investors"],
  },
  {
    id: "7",
    title: "Backend Development",
    thumbnailColor: "#B79FE0",
    lecturerName: "Timilehin Josiah",
    category: "Digital Marketing",
    department: "Computer Science",
    amount: "₦150,000",
    enrolledStudents: 250,
    earnedByLecturer: "₦450,000",
    earnedByInstitution: "₦450,000",
    type: "Advanced",
    dateCreated: "12-02-2026",
    courseCode: "CSC 320",
    pricing: "Paid",
    detailAmount: "₦150,000",
    detailEarnedByLecturer: "₦450,000",
    detailEarnedByInstitution: "₦450,000",
    modules: 7,
    lessons: 21,
    status: "Active",
    description: "Server-side development with modern frameworks.",
    whatTheyWillLearn: ["REST API design", "Databases & ORMs", "Authentication & security basics"],
  },
];
