import React from "react";

import { Inter } from "next/font/google";

// eslint-disable-next-line import/order
import AuthLayout from "@spt/layouts/authLayout";

import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AuthLayout>{children}</AuthLayout>
      </body>
    </html>
  );
}
