"use client";

import type { CommunityCardItem } from "./communityTypes";

export const communityFilters = [
  { value: "all", label: "All Communities" },
  { value: "free", label: "Free Communities" },
  { value: "locked", label: "Locked Communities" },
] as const;

export type CommunityFilterValue = (typeof communityFilters)[number]["value"];

export const exploreCommunities: CommunityCardItem[] = [
  {
    id: "design-principles",
    name: "Design Principles",
    description: "This is the community for design principles learners.",
    audience: "free",
    members: 80,
    avatarLabel: "DP",
    accentColor: "#151C3B",
  },
  {
    id: "frontend-development",
    name: "Frontend Development",
    description: "Discuss the latest in technology and stay ahead of the curve.",
    audience: "free",
    members: 124,
    avatarLabel: "FE",
    accentColor: "#6E9BC3",
  },
  {
    id: "medical-laboratory",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "locked",
    members: 92,
    avatarLabel: "ML",
    accentColor: "#F0B98A",
  },
  {
    id: "branding",
    name: "Branding",
    description: "Dive into the world of HTML, CSS, and JavaScript mastery.",
    audience: "free",
    members: 104,
    avatarLabel: "BR",
    accentColor: "#3B312A",
  },
  {
    id: "design-principles-two",
    name: "Design Principles",
    description: "This is the community for design principles learners.",
    audience: "free",
    members: 80,
    avatarLabel: "DP",
    accentColor: "#151C3B",
  },
  {
    id: "medical-laboratory-two",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "locked",
    members: 98,
    avatarLabel: "ML",
    accentColor: "#F0B98A",
  },
  {
    id: "medical-laboratory-three",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 112,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-laboratory-four",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "locked",
    members: 99,
    avatarLabel: "ML",
    accentColor: "#F0B98A",
  },
  {
    id: "medical-laboratory-five",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "locked",
    members: 84,
    avatarLabel: "ML",
    accentColor: "#F0B98A",
  },
  {
    id: "frontend-development-two",
    name: "Frontend Development",
    description: "Discuss the latest in technology and stay ahead of the curve.",
    audience: "free",
    members: 126,
    avatarLabel: "FE",
    accentColor: "#6E9BC3",
  },
  {
    id: "medical-laboratory-six",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "locked",
    members: 97,
    avatarLabel: "ML",
    accentColor: "#F0B98A",
  },
  {
    id: "branding-two",
    name: "Branding",
    description: "Dive into the world of HTML, CSS, and JavaScript mastery.",
    audience: "free",
    members: 101,
    avatarLabel: "BR",
    accentColor: "#3B312A",
  },
];

export const learnerJoinedCommunities: CommunityCardItem[] = [
  {
    id: "frontend-community",
    name: "Frontend Development",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "FE",
    accentColor: "#6E9BC3",
  },
  {
    id: "finance-community",
    name: "Finance",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "FI",
    accentColor: "#C8D4E3",
  },
  {
    id: "business-management-community",
    name: "Business Management",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "BM",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community-two",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "design-principles-community",
    name: "Design Principles",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "DP",
    accentColor: "#C8D4E3",
  },
  {
    id: "product-design-community",
    name: "Product Design",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "PD",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community-three",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community-four",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community-five",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community-six",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-community-seven",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
];

export const tutorCreatedCommunities: CommunityCardItem[] = [
  {
    id: "backend-development-community",
    name: "Backend Development",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "BE",
    accentColor: "#C8D4E3",
  },
  {
    id: "analytical-thinking-community",
    name: "Analytical Thinking",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "AT",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "finance-created-community",
    name: "Finance",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "FI",
    accentColor: "#C8D4E3",
  },
  {
    id: "pharmacology-created-community",
    name: "Pharmacology",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "PH",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-two",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-three",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-four",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-five",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-six",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-seven",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
  {
    id: "medical-lab-created-community-eight",
    name: "Medical Laboratory",
    description: "Fuel your creativity with ideas, tips, and collaboration here.",
    audience: "free",
    members: 100,
    avatarLabel: "ML",
    accentColor: "#C8D4E3",
  },
];
