"use client";

import { useState } from "react";

import { Pagination } from "@spt/components";

import RevenueSplitCard from "../../../../components/RevenueSplitCard";
import { BookIcon } from "../../../components/icons";

import { EARNINGS_SUMMARY, MOCK_EARNINGS_BREAKDOWN } from "./constants";
import EarningsStatCard from "./EarningsStatCard";

const SearchInput = ({
  value,
  onChange,
  placeholder,
}: {
  value: string;
  onChange: (value: string) => void;
  placeholder: string;
}) => (
  <div className="flex w-full max-w-sm items-center gap-2 rounded-lg border border-gray-200 px-3 py-2">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <circle cx="11" cy="11" r="7" stroke="#9CA3AF" strokeWidth="1.8" />
      <path d="M20 20l-3.5-3.5" stroke="#9CA3AF" strokeWidth="1.8" strokeLinecap="round" />
    </svg>
    <input
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      className="w-full text-sm outline-none placeholder:text-gray-400"
    />
  </div>
);

const EarningsTab = () => {
  const [search, setSearch] = useState("");
  const [activePage, setActivePage] = useState(1);

  const filtered = MOCK_EARNINGS_BREAKDOWN.filter((item) =>
    item.title.toLowerCase().includes(search.trim().toLowerCase()),
  );

  return (
    <div className="space-y-6">
      <p className="text-sm text-gray-500">
        View the revenue generated by this lecturer and see how earnings are shared between the institution
        and the lecturer.
      </p>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <EarningsStatCard
          tone="blue"
          icon={<BookIcon color="#fff" />}
          label="Total Gross Revenue"
          value={EARNINGS_SUMMARY.totalGrossRevenue}
        />
        <EarningsStatCard
          tone="orange"
          icon={<BookIcon color="#fff" />}
          label="Total Lecturer Earnings"
          value={EARNINGS_SUMMARY.totalLecturerEarnings}
        />
        <EarningsStatCard
          tone="purple"
          icon={<BookIcon color="#fff" />}
          label="Total Institution Earnings"
          value={EARNINGS_SUMMARY.totalInstitutionEarnings}
        />
      </div>

      <RevenueSplitCard
        lecturerPercent={EARNINGS_SUMMARY.lecturerSplitPercent}
        institutionPercent={EARNINGS_SUMMARY.institutionSplitPercent}
      />

      <div className="space-y-5 rounded-2xl border border-gray-100 bg-white p-6 sm:p-8">
        <h3 className="text-lg font-semibold text-[#212529]">Earnings Breakdown</h3>

        <SearchInput value={search} onChange={setSearch} placeholder="Search for a Spoylz..." />

        <div className="overflow-x-auto">
          <table className="w-full min-w-[900px] border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-gray-100 text-gray-400">
                <th className="py-3 pr-4 font-medium">S/N</th>
                <th className="py-3 pr-4 font-medium">Spoylz Title</th>
                <th className="py-3 pr-4 font-medium">Spoylz Amount</th>
                <th className="py-3 pr-4 font-medium">Enrolled Students</th>
                <th className="py-3 pr-4 font-medium">Gross Revenue</th>
                <th className="py-3 pr-4 font-medium">Lecturer Share</th>
                <th className="py-3 pr-4 font-medium">Institution Share</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((item, index) => (
                <tr key={item.id} className="border-b border-gray-50">
                  <td className="py-4 pr-4 text-gray-500">{index + 1}</td>
                  <td className="py-4 pr-4">
                    <div className="flex items-center gap-3">
                      <span
                        className="h-9 w-9 shrink-0 rounded-lg"
                        style={{ backgroundColor: item.thumbnailColor }}
                      />
                      <span className="text-[#212529]">{item.title}</span>
                    </div>
                  </td>
                  <td className="py-4 pr-4 text-[#212529]">{item.amount}</td>
                  <td className="py-4 pr-4 text-[#212529]">{item.enrolledStudents}</td>
                  <td className="py-4 pr-4 text-[#212529]">{item.grossRevenue}</td>
                  <td className="py-4 pr-4 text-gray-400 line-through">{item.lecturerShare}</td>
                  <td className="py-4 pr-4 text-[#212529]">{item.institutionShare}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <Pagination activePage={activePage} onPageChange={setActivePage} />
      </div>
    </div>
  );
};

export default EarningsTab;
