import { Inter } from "next/font/google";

import Footer from "@spt/layouts/footer/footer";
import Header from "@spt/layouts/website/header";

import type { Metadata } from "next";
import "../globals.css";
import QueryProvider from "../providers/QueryProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Spoilert Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </QueryProvider>
    </html>
  );
}
