name: Deploy Next.js (Standalone) to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Create .env
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" > .env
          echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" >> .env
          echo "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}" >> .env

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js (Standalone)
        run: |
          rm -rf .next
          yarn build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          rsync -avz --delete \
            .next/standalone/ \
            $SERVER_USER@$SERVER_IP:/var/www/spoilert-web-app/standalone/

          rsync -avz --delete \
            .next/static/ \
            $SERVER_USER@$SERVER_IP:/var/www/spoilert-web-app/static/

          rsync -avz --delete \
            public \
            .env \
            ecosystem.config.cjs \
            $SERVER_USER@$SERVER_IP:/var/www/spoilert-web-app/

          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/spoilert-web-app
            pm2 reload ecosystem.config.cjs --env production
            pm2 save
            sudo systemctl reload nginx
          EOF
